# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : title
tagline: yep
author :
  name : Matt Hughes
  email : hughesm02@gmail.com
  github : hughes

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://hughes.github.com

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13

  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive.html
  tags_path : /tags.html

  comments :
    provider : disqus
    disqus :
      short_name : hughes-pages

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-36226098-1'

  sharing :
    provider : false
  
paginate: 3

